name = "SoilProfiles"
uuid = "d2d87a28-bc46-4564-bd1b-2e333645c2dc"
authors = ["Andrew G. Brown <andrew.g.brown@usda.gov>"]
version = "0.2.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
DataFrames = "0.21"
